/** Declaration file generated by dts-gen */

export class Luxafor {
  constructor(...args: any[]);

  color(...args: any[]): void;

  colorFade(...args: any[]): void;

  flushBuffer(...args: any[]): void;

  init(...args: any[]): void;

  newBuffer(...args: any[]): void;

  pattern(...args: any[]): void;

  readBuffer(...args: any[]): void;

  simpleColor(...args: any[]): void;

  strobe(...args: any[]): void;

  wave(...args: any[]): void;

  static getApiValue(...args: any[]): void;
}

export const API: {
  BYTE: {
    BLUE: number;
    COMMAND: number;
    GREEN: number;
    LED: number;
    PATTERN_ID: number;
    PATTERN_REPEAT: number;
    RED: number;
    SPEED: number;
    STROBE_PADDING: number;
    STROBE_REPEAT: number;
    TIME: number;
    WAVE_PADDING: number;
    WAVE_REPEAT: number;
    WAVE_SPEED: number;
    WAVE_TYPE: number;
  };
  COLOR: {
    BLUE: number;
    CYAN: number;
    GREEN: number;
    MAGENTA: number;
    OFF: number;
    RED: number;
    WHITE: number;
    YELLOW: number;
  };
  COMMAND: {
    PATTERN: number;
    SET_COLOR_FADE: number;
    SET_COLOR_NO_FADE: number;
    SET_COLOR_SIMPLE: number;
    STROBE: number;
    WAVE: number;
  };
  LED: {
    ALL: number;
    LED_1: number;
    LED_2: number;
    LED_3: number;
    LED_4: number;
    LED_5: number;
    LED_6: number;
    SIDE_A: number;
    SIDE_B: number;
  };
  PATTERNS: {
    "1": number;
    "2": number;
    "3": number;
    "4": number;
    "5": number;
    "6": number;
    "7": number;
    UNKNOWN_1: number;
    UNKNOWN_2: number;
    UNKNOWN_3: number;
    UNKNOWN_4: number;
    UNKNOWN_5: number;
    UNKNOWN_6: number;
    UNKNOWN_7: number;
    UNKNOWN_8: number;
  };
  PID: number;
  VID: number;
  WAVE_TYPE: {
    "1": number;
    "2": number;
    "3": number;
    "4": number;
    "5": number;
    UNKNOWN_1: number;
    UNKNOWN_2: number;
    UNKNOWN_3: number;
    UNKNOWN_4: number;
    UNKNOWN_5: number;
  };
};
